### DISCUSSION TITLE
📄 [문서] YML 파일 분리 및 환경변수 설정

### DISCUSSION THREAD

**Discussion by Chuseok22** [TEAM-ROMROM/RomRom-BE#1] [Documents]
🗒️ 설명
---
## YML 파일
```
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/여러분이 만든 Database이름 (전 sejong_balsamic 으로함)
    username: {여러분이 만든 아이디}
    password: {여러분이 만든 비밀번호}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE\
```
1. resources 폴더 안에 application-dev.yml 파일을 만듭니다 (내용은 위와 같음, 예시는 MariaDB 이므로 PostgreSQL, MongoDB 찾아서 수정하면 됩니다~)
기본적으로 본인 컴퓨터에 DB가 설치되어있고 사용할 Database를 생성해야합니다
개발 설정파일과 본 서버에 올라갈 설정파일을 분리하기 위해 YML 파일을 다르게 설정합니다

![스크린샷 2025-01-07 오후 1 56 04](https://github.com/user-attachments/assets/0d811fd6-d957-4d65-875f-61006e3e555d)
다음과 같이 3개의 파일이 존재해야합니다
application.yml은 기본적으로 prod가 active되어있는 상태입니다
하지만 개발환경에서는 명시적으로 application-dev.yml파일을 active 시켜야하기때문에 프로그램 인수를 설정해야합니다

![스크린샷 2025-01-07 오후 1 57 30](https://github.com/user-attachments/assets/380f6b6c-1b91-4b5e-85b9-f0217d42491c)

![스크린샷 2025-01-07 오후 1 59 16](https://github.com/user-attachments/assets/04f2b9ca-8cfb-48b1-97ba-80638360bc23)
다음과 같이 설정합니다
Active profiles에 다음 값을 넣으면 됩니다
`dev`

우리는 application-dev.yml, application-prod.yml파일을 gitignore 된 상태로 진행할겁니다
즉 github에는 application.yml 파일만 올라가게됩니다
당연히 application.yml 파일에는 민감한 정보 (db host, password 등등)가 작성되면 안되겠죠?
application-dev.yml 파일은 로컬에서 사용하는 정보가 작성되면 되고, application-prod.yml파일은 Git Secret로 등록해서 빌드시 적용되게 할겁니다

application-prod.yml파일은 수정되는경우 채팅방에서 변경사항 공유해주시면 됩니다~

### application-dev.yml 예시
```
spring:
  datasource:
    # PostgreSQL 설정
    url: jdbc:postgresql://localhost:5432/{database_name}
    username: {username}
    password: {password}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      # MongoDB 설정
      host: localhost
      port: 27017
      database: {database_name}
      username: {username}
      password: {password}
    redis:
      host: localhost
      port: 6379
      password: {password}
      connection-pool-size: 10
      connection-minimum-size: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
```
본인 로컬 PC환경에 맞춰 수정하시면됩니다

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 @Cassiiopeia @seopgyu 
- 프론트엔드: 이름
- 디자인: 이름
