### ISSUE TITLE
🔧 [기능요청][임베딩] Pgvector를 활용한 물품&카테고리 임베딩 값 저장

### ISSUE THREAD

**Issue by Chuseok22** [TEAM-ROMROM/RomRom-BE#126]
🛠️ 설명
---

### Suh-Project 내부 경로
* /docker/docker-compose/postgres 경로에 `docker-compose.yml`, `Dockerfile` 이 작성되어있습니다
* `Dockerfile`: 도커 이미지를 pull 하기 위한 설정파일
* `docker-compose.yml`: 도커 컨테이너를 올리기 위한 설정파일

#### Dockerfile
```
FROM postgres:14

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    git \
    make \
    gcc \
    postgresql-server-dev-14 \
    && git clone https://github.com/pgvector/pgvector.git \
    && cd pgvector && make && make install \
    && rm -rf /pgvector \
    && apt-get remove -y git make gcc \
    && apt-get autoremove -y && apt-get clean
```
* Dockerfile 파일 설정을 보면 `postgres 14`버전을 pull할 때 자동으로 `pgvector`를 설치합니다

#### docker-compose.yml
```
version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5430:5432"  # 호스트의 5430 포트를 컨테이너의 5432 포트로 매핑
    volumes:
      - /volume1/docker/postgres:/var/lib/postgresql/data  # /volume1/docker/postgres 매핑
```
* yml파일을 보면 위에 작성한 Dockerfile을 통해 설정한 이미지를 컨테이너로 올리고 있습니다
* 내부 환경변수는 삭제했습니다

-> 로컬에서 임베딩 사용 시 `pgvector` 익스텐션 설치가 필수적입니다

## Entity
@Chuseok22 설계후 이슈 업데이트 하겠습니다

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: 이름
- 디자인: 이름
