### ISSUE TITLE
⚙️ [기능추가][codeRabbit] codeRabbit 설정 파일 추가

### ISSUE THREAD

**Issue by Chuseok22** [TEAM-ROMROM/RomRom-BE#136]
📝 현재 문제점
---

- `feat` -> `test` PR 설정 시 자동 리뷰가 안되는 문제

🛠️ 해결 방안 / 제안 기능
---

https://docs.coderabbit.ai/getting-started/configure-coderabbit/
- root 경로에 `coderabbit.yaml` 파일 추가합니다

🙋‍♂️ 담당자
---
- 백엔드: 이름
- 프론트엔드: 이름
- 디자인: 이름

**Comment by Chuseok22** [comment]
```
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR"
ignored_branch: ""
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - test
      - main
chat:
  auto_reply: true
```

`base_branches`추가했습니다
