### ISSUE TITLE
🔧 [기능요청][임베딩] 임베딩 JSON 파일 저장하는 CICD 로직 추가

### ISSUE THREAD

**Issue by discipline24** [TEAM-ROMROM/RomRom-BE#145]
📝 현재 문제점
---

파일 이름: gen-lang-client-0511951522-a173c85ef515.json
GitHub Secrets 키 이름: VERTEX_SA_KEY
value 내용: gen-lang-client-0511951522-a173c85ef515.json 파일 전체 내용을 문자열 형태로 Secrets에 저장함 (줄바꿈 포함된 JSON 원문 전체)

프로젝트 내부 경로: /src/main/resources/gen-lang-client-0511951522-a173c85ef515.json에 파일을 복사해 사용

현재 GitHub Actions에서 CI/CD 빌드 시 위 JSON 키 파일이 존재하지 않기 때문에, Google 인증 과정에서 FileNotFoundException이 발생하며 배포가 실패합니다.

🛠️ 해결 방안 / 제안 기능
---
CI/CD에서 VERTEX_SA_KEY GitHub Secrets 값을 가져와 JSON 파일로 복원하고 /src/main/resources/gen-lang-client-0511951522-a173c85ef515.json 경로에 저장하는 로직 추가

예시 스크립트 (GitHub Actions deploy.yml에 추가):

- name: 서비스 계정 키 파일 생성
  run: |
    echo "${{ secrets.VERTEX_SA_KEY }}" > src/main/resources/vertex-service-account.json

이 과정은 JAR 빌드 전에 반드시 실행되어야 합니다. (./gradlew build 앞에 위치)

⚙️ 작업 내용
---
- GitHub Actions 워크플로우에서 비밀키 JSON 파일을 생성하도록 단계 추가 
- 인증 실패 방지 및 Vertex AI 호출 가능하게 구성 

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: 이름
- 디자인: 이름

**Comment by Cassiiopeia** [comment]
@discipline24  자세하게 써주셨군요 넵넵 확인했습니다

**Comment by Cassiiopeia** [comment]
작업 완료했습니다

1. .github/workflows/ROMROM-BE-CICD.yaml 파일에 다음 단계 추가:
```
- name: Create Vertex AI Service Account Key
  env:
    VERTEX_SA_KEY: ${{ secrets.VERTEX_SA_KEY }}
  run: |
    echo "$VERTEX_SA_KEY" | sed 's/\\n/\n/g' > ./src/main/resources/gen-lang-client-0511951522-a173c85ef515.json
```
2. .github/workflows/ROMROM-BE-CD.yaml 파일에도 동일한 단계 추가:
```
- name: Create Vertex AI Service Account Key
  env:
    VERTEX_SA_KEY: ${{ secrets.VERTEX_SA_KEY }}
  run: |
    echo "$VERTEX_SA_KEY" | sed 's/\\n/\n/g' > ./src/main/resources/gen-lang-client-0511951522-a173c85ef515.json
```

다음과 같이 추가했습니다

PR 올려서 정상 빌드되는지 확인 부탁드립니다

@discipline24
